---
dropdown:
  - name: Home
    src: some-link-to-another-yaml-raw-file
    action: home
  - name: Designs
    src: some-link-to-another-yaml-raw-file
    action: table
  - name: Components
    src: some-link-to-another-yaml-raw-file
    action: table
# this section above will be in every yaml

card:
  - name: Designs
    description: some-description-about-designs
    image: some-link-to-raw-img-file
    src: some-link-to-another-yaml-raw-file
    action: table
  - name: Components
    description: Some-description-about-components
    image: some-link-to-raw-img-file
    src: some-link-to-another-yaml-raw-file
    action: table
  - name: GitHub
    description: Some-description-about-gitpage
    image: some-link-to-raw-img-file
    src: some-link-to-another-yaml-raw-file
    action: web
  - name: AguaClara Website
    description: Some-description-about-aguasite
    image: some-link-to-raw-img-file
    src: some-link-to-another-yaml-raw-file
    action: web
...
