---
dropdown:
  - name: Home
    src: https://raw.githubusercontent.com/AguaClara/aide_gui/spring-2018/aide_gui/palette_docs/home/base.yaml
    action: home
  - name: Designs
    src: https://raw.githubusercontent.com/AguaClara/aide_gui/spring-2018/aide_gui/palette_docs/home/designTable.yaml
    action: table
  - name: Components
    src: https://raw.githubusercontent.com/AguaClara/aide_gui/spring-2018/aide_gui/palette_docs/home/componentTable.yaml
    action: table
# this section above will be in every yaml

card:
  - name: Designs
    description: some-description-about-designs
    image: https://raw.githubusercontent.com/AguaClara/aide_gui/spring-2018/aide_gui/palette_docs/home/design.png
    src: https://raw.githubusercontent.com/AguaClara/aide_gui/spring-2018/aide_gui/palette_docs/home/designTable.yaml
    action: table
  - name: Components
    description: Some-description-about-components
    image: https://raw.githubusercontent.com/AguaClara/aide_gui/spring-2018/aide_gui/palette_docs/home/component.png
    src: https://raw.githubusercontent.com/AguaClara/aide_gui/spring-2018/aide_gui/palette_docs/home/componentTable.yaml
    action: table
  - name: GitHub
    description: Some-description-about-gitpage
    image: some-link-to-raw-img-file
    src: some-link-to-another-yaml-raw-file
    action: web
  - name: AguaClara Website
    description: Some-description-about-aguasite
    image: some-link-to-raw-img-file
    src: http://aguaclara.cornell.edu
    action: web
...
